server:
  port: 8080
#第一种配置方法
name1: caipch
age1: 22

#第二种配置方法
name2: caipch
age2: 22
content: "name:${name2},age:${age2}"

#第三种配置方法
student: 
  name3: caipch
  age3: 22
  
swagger:
  basePackage: com.pc.springbootdemo.controller
  title: caipch
  description: swagger
  version: V1.0

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
#配置数据源
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: tiger
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent-output: true

